apiVersion: v1
kind: Secret
metadata:
  {{- if not .Values.zsglobal.multiConnector.enabled }}
  name: {{ .Values.zsglobal.secretIdentifier }}
  {{- else }}
  name: {{ .Values.zsglobal.multiConnector.secretIdentifier }}
  {{- end }}
  labels:
    {{- include "zpa-app-connector-openshift.labels" . | nindent 4 }}
  namespace: {{ .Values.zsglobal.namespace }}
type: Opaque
stringData:
    provisionkey: {{ .Values.zsglobal.provisionkey.value }}