---
{{- if not .Values.zsglobal.multiConnector.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.zsglobal.serviceAccount.name }}
  labels:
    {{- include "zpa-app-connector-openshift.labels" . | nindent 4 }}
  namespace: {{ .Values.zsglobal.namespace }}
 {{- end }}
